import _ from "../html/browser-source.html"
import _1 from "../html/control-panel.html"
import _2 from "../html/debug.html"
import * as _3 from "./browser-source"
import * as _4 from "./control-panel"
